<?xml version="1.0" encoding="UTF-8"?><RuntimeErrorAnalysis><AuthorAffiliation>Community</AuthorAffiliation><Summary>CleanupFailureDataAccessException</Summary><SampleLogOutput><![CDATA[CleanupFailureDataAccessException]]></SampleLogOutput><RegExpPattern><![CDATA[CleanupFailureDataAccessException]]></RegExpPattern><ProblemDetailHtml><![CDATA[Exception thrown when we couldn't cleanup after a data access operation,
 but the actual operation went OK.

 <p>For example, this exception or a subclass might be thrown if a JDBC
 Connection couldn't be closed after it had been used successfully.

 <p>Note that data access code might perform resources cleanup in a
 finally block and therefore log cleanup failure rather than rethrow it,
 to keep the original data access exception, if any.]]></ProblemDetailHtml><SolutionDetailHtml><![CDATA[Common solutions for this exception have not yet been submitted.]]></SolutionDetailHtml><AdditionalResourcesDetailHtml></AdditionalResourcesDetailHtml></RuntimeErrorAnalysis>